- name: Add apt repo for go
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ http_proxy }}"
  apt_repository:
    repo: ppa:longsleep/golang-backports
    state: present
    filename: google-chrome
  become: true

- name: apt golang-go
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ http_proxy }}"
  apt:
    name: golang-go
    state: present
  become: true
