# Font configuration
font:
  normal:
    family: CodeNewRoman NF
    style: Book

  bold:
    family: CodeNewRoman NF
    style: Bold

  italic:
    family: CodeNewRoman NF
    style: Italic

  # Bold italic font face
  #bold_italic:
    # Font family
    #
    # If the bold italic family is not specified, it will fall back to the
    # value specified for the normal font.
    #family: monospace

    # The `style` can be specified to pick a specific face.
    #style: Bold Italic

  # Point size
  size: 12.0

colors:
  # Default colors
  primary:
    # hard contrast: background = '#1d2021'
    background: '#282828'
    # soft contrast: background = '#32302f'
    foreground: '#ebdbb2'

  # Normal colors
  normal:
    black:   '#282828'
    red:     '#cc241d'
    green:   '#98971a'
    yellow:  '#d79921'
    blue:    '#458588'
    magenta: '#b16286'
    cyan:    '#689d6a'
    white:   '#a89984'

  # Bright colors
  bright:
    black:   '#928374'
    red:     '#fb4934'
    green:   '#b8bb26'
    yellow:  '#fabd2f'
    blue:    '#83a598'
    magenta: '#d3869b'
    cyan:    '#8ec07c'
    white:   '#ebdbb2'

key_bindings:
  - { key: Up, mods: Control, action: ScrollLineUp }
  - { key: Down, mods: Control, action: ScrollLineDown }
  - { key: Up, mods: Shift|Control, action: ScrollPageUp }
  - { key: Down, mods: Shift|Control, action: ScrollPageDown }
