- name: install shadowsocks
  apt:
    name: shadowsocks-libev
  become: yes

- name: add shadowsocks-server systemd config
  template:
    src: shadowsocks-server.service
    dest: /etc/systemd/system/shadowsocks-server.service
  become: yes

- name: enable shadowsocks-server systemd service
  systemd:
    name: shadowsocks-server.service
    state: started
    enabled: yes
  become: yes

