all:
  vars:
    ansible_user: hadi 
    ansible_ssh_pipelining: yes
    ansible_python_interpreter: /usr/bin/python3
    kubelet_environment_file_path: /etc/default/kubelet
    kubelet_systemd_extra_file_path: /etc/systemd/system/kubelet.service.d/99-extra.conf
    kubernetes_kubelet_extra_args: []
  children:
    masters:
      hosts:
        tnode:
          ansible_host: 10.20.20.57
          #ansible_host: localhost
          #ansible_connection: local
    # workers:
    #   hosts: []
