- name: install shadowsocks
  apt:
    name: shadowsocks-libev
  become: yes

- name: add shadowsocks-client systemd config
  template:
    src: shadowsocks-client.service
    dest: /etc/systemd/system/shadowsocks-client.service
  become: yes

- name: enable shadowsocks-client systemd service
  systemd:
    name: shadowsocks-client.service
    state: started
    enabled: yes
  become: yes

