- name: add alacritty ppa
  apt_repository:
    repo: ppa:mmstick76/alacritty
    state: present
  become: yes

- name: install alacritty
  apt:
    name: terminator
  become: yes


- name: terminator config
  template:
    src: alacritty.yml
    dest: ~/.alacritty.yml
