- name: add docker repository gpg key
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ http_proxy }}"
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: yes

- name: add docker source list
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ http_proxy }}"
  apt_repository:
    repo: "deb https://download.docker.com/linux/ubuntu bionic stable"
    state: present
    filename: docker
  become: yes

- name: pin docker version
  copy:
    dest: /etc/apt/preferences.d/pin-docker
    content: |
      Package: docker-ce
      Pin: "version {{ docker_version }}"
      Pin-Priority: 1001
  become: yes

- name: install docker packages
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ http_proxy }}"
  apt:
    package:
    - docker-ce
    state: present
    update_cache: yes
  become: yes

- name: create docker config directory
  file:
    path: "{{ item }}"
    state: directory
  loop:
  - /etc/docker
  - /etc/systemd/system/docker.service.d
  become: yes

- name: configure docker
  copy:
    dest: /etc/docker/daemon.json
    content: |
      {
        "exec-opts": ["native.cgroupdriver=systemd"],
        "log-driver": "json-file",
        "log-opts": {
          "max-size": "100m"
        },
        "storage-driver": "overlay2",
        "live-restore": true
      }
  become: yes

- name: set docker proxy
  copy:
    dest: /etc/systemd/system/docker.service.d/http-proxy.conf
    content: |
      [Service]
      Environment=NO_PROXY={{ no_proxy }}
      Environment=HTTP_PROXY={{ http_proxy }}
      Environment=HTTPS_PROXY={{ http_proxy }}
  when: http_proxy is defined
  become: yes

- name: restart docker
  systemd:
    name: docker
    state: restarted
    daemon_reload: yes
    enabled: yes
  become: yes

- name: download docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.21.2/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: '0771'
  become: yes

